version : 2.1

executors:
  ubuntu:
    machine:
      image: circleci/classic:latest

jobs:
  build_api:
    parameters:
      api_base_dir:
        type: string
      api_tests_dir:
        type: string
      dotnet_version:
        type: string
    executor: ubuntu
    working_directory: ~/project
    steps:
      - checkout:
          path: ~/project
      - run: sudo sysctl -n -w fs.inotify.max_user_instances=512

workflows:
  version: 2.1
  rest_api:
    jobs:
      - build_api:
          name: build-rest-api
          api_base_dir: src/Portfolio.Api
          api_tests_dir: src/Portfolio.Tests
          dotnet_version: "3.1.100"
