version : 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: Restore Packages API
          command: dotnet restore
          working_directory: src/Portfolio.Api
      - run:
          name: Restore Packages Tests
          command: dotnet restore
          working_directory: src/Portfolio.Tests
      - run:
          name: Run Tests
          command: dotnet test
          working_directory: src/Portfolio.Tests
      - run:
          name: Run Build
          command: dotnet build
          working_directory: src/Portfolio.Api
