version : 2.1

executors:
  ubuntu:
    machine:
      image: circleci/classic:latest

jobs:
  build:
    executor: ubuntu
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
          working_directory: Portfolio.Api
      - run:
          name: Build
          command: dotnet build -c Release
          working_directory: Portfolio.Api
      - run:
          name: Running Tests
          command: dotnet test
          working_directory: Portfolio.Tests
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build -t Portfolio .
