version : 2.1

executors:
  ubuntu:
    machine:
      image: circleci/classic:latest

jobs:
  test:
    description: Setup and run application tests
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: dotnet restore
      - run:
          name: "Run Application Tests"
          command: dotnet test
  build:
    description: Build application with Release configuration
    steps:
      - checkout
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet build
workflows:
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test
