version : 2.1

commands:
  codecov:
    parameters:
      file:
        type: string
    steps:
      - run:
          name: Download Codecov script
          command: curl -s https://codecov.io/bash > ./codecov
      - run:
          name: Make Codecov script executable
          command: chmod +x ./codecov
      - run:
          name: Send coverage report
          command: ./codecov -f << parameters.file >> -t $CODECOV_TOKEN

executors:
  ubuntu:
    machine:
      image: circleci/classic:latest

jobs:
  build_api:
    parameters:
      api_base_dir:
        type: string
      api_tests_dir:
        type: string
      dotnet_version:
        type: string
    executor: ubuntu
    working_directory: ~/project
    steps:
      - checkout:
          path: ~/project
      - run: sudo sysctl -n -w fs.inotify.max_user_instances=512
      - run: sudo chmod +x ./tools/install-dotnet.sh
      - run: ./tools/install-dotnet.sh << parameters.dotnet_version >>
      - run: sudo chmod +x ./tools/test.sh
      - run: ./tools/test.sh
      - codecov:
          file: << parameters.api_tests_dir >>/coverage/coverage.opencover.xml
      - store_artifacts:
          path: << parameters.api_tests_dir >>/ccoveragereport/summary.htm
          destination: << parameters.api_base_dir >>/coverage-report.htm

workflows:
  version: 2.1
  rest_api:
    jobs:
      - build_api:
          name: build-rest-api
          api_base_dir: src/Portfolio.Api
          api_tests_dir: src/Portfolio.Tests
          dotnet_version: "3.1.100"
