version: 2.1

orbs:
  codecov: codecov/codecov@3.0.0

executors:
  dotnet-executor:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1.416

jobs:
  build_api:
    parameters:
      api_base_dir:
        type: string
      api_tests_dir:
        type: string
    executor: dotnet-executor
    steps:
      - checkout
      - run:
          name: Restore Packages API
          command: dotnet restore
          working_directory: << parameters.api_base_dir >>
      - run:
          name: Restore Packages Tests
          command: dotnet restore
          working_directory: << parameters.api_tests_dir >>
      - run:
          name: Run Tests
          command: dotnet test \
                  /p:AltCover="true" \
                  /p:AltCoverForce="true" \
                  /p:AltCoverThreshold="80" \
                  /p:AltCoverOpenCover="true" \
                  /p:AltCoverXmlReport="coverage/opencover.xml" \
                  /p:AltCoverInputDirectory=<< parameters.api_base_dir >> \
                  /p:AltCoverAttributeFilter="ExcludeFromCodeCoverage" \
                  /p:AltCoverAssemblyExcludeFilter="System(.*)|xunit|<< parameters.api_tests_dir >>|<< parameters.api_base_dir >>.Views" \

                  dotnet reportgenerator \
                  "-reports:coverage/opencover.xml" \
                  "-reporttypes:Html;HtmlSummary" \
                  "-targetdir:coverage/report"
          working_directory: << parameters.api_tests_dir >>
      - run:
          name: Run Build
          command: dotnet build
          working_directory: << parameters.api_base_dir >>
      - codecov/upload:
          token: CODECOV_TOKEN
          file: << parameters.api_tests_dir >>/coverage/opencover.xml

workflows:
  version: 2.1
  rest_api:
    jobs:
      - build_api:
          name: build-rest-api
          api_base_dir: src/Portfolio.Api
          api_tests_dir: src/Portfolio.Tests
