version : 2.1

orbs:
  codecov: codecov/codecov@3.0.0

jobs:
  build_api:
    parameters:
      api_base_dir:
        type: string
      api_tests_dir:
        type: string
    docker:
    - image: mcr.microsoft.com/dotnet/core/sdk:3.1.416
    steps:
      - checkout
      - run:
          name: Restore Packages API
          command: dotnet restore
          working_directory: << parameters.api_base_dir >>
      - run:
          name: Restore Packages Tests
          command: dotnet restore
          working_directory: << parameters.api_tests_dir >>
      - run:
          name: Run Tests
          command: dotnet test
          working_directory: << parameters.api_tests_dir >>
      - run:
          name: Run Build
          command: dotnet build
          working_directory: << parameters.api_base_dir >>
      - codecov/upload:
          token: CODECOV_TOKEN

workflows:
  version: 2.1
  rest_api:
    jobs:
      - build_api:
          name: build-rest-api
          api_base_dir: src/Portfolio.Api
          api_tests_dir: src/Portfolio.Tests
