@categoryId = 01FPRHPPW1HQSJHJ5ANQTNNMX2

GET {{baseUrl}}/categories
Content-Type: application/json

###

GET {{baseUrl}}/categories/{{categoryId}}
Content-Type: application/json

###

POST {{baseUrl}}/categories
Content-Type: application/json

{
  "name": "Productivity"
}

###

PUT {{baseUrl}}/categories/{{categoryId}}
Content-Type: application/json

{
  "name": "Technology",
}

###

DELETE {{baseUrl}}/categories/{{categoryId}}
Content-Type: application/json
